USE [EACC]
GO

/****** Object:  Table [dbo].[TEA_TEAM]    Script Date: 09/09/2009 14:41:58 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[[[ACH_ACHIEVMENT]]]') AND type in (N'U'))
DROP TABLE [dbo].[ACH_ACHIEVMENT]
GO

USE [EACC]
GO
CREATE TABLE [dbo].[ACH_ACHIEVMENT](
	[ACH_ID] [int] NOT NULL identity,
	[ACH_NAME_CH] [nvarchar](500) NOT NULL,
	[ACH_DESCR_CH] [nvarchar](500) NOT NULL,
	[ACH_IMG_CH] [nvarchar](500) NOT NULL
 CONSTRAINT [PK_ACH_ACHIEVMENT] PRIMARY KEY CLUSTERED 
(
	[ACH_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO