USE [EACC]
GO

/****** Object:  Table [dbo].[MOD_MODULE]    Script Date: 09/09/2009 14:41:58 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MOD_MODULE]') AND type in (N'U'))
DROP TABLE [dbo].[MOD_MODULE]
GO

USE [EACC]
GO
CREATE TABLE [dbo].[MOD_MODULE](
	[MOD_ID] [int] NOT NULL identity,
	[MOD_NAME_CH] [nvarchar](500) NOT NULL,
	[MOD_TYPE_NU] [int] NOT NULL,
	[VCL_ID] [int] NOT NULL,
 CONSTRAINT [PK_MOD_MODULE] PRIMARY KEY CLUSTERED 
(
	[MOD_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

